name: Check pub score

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-score:
    name: Check pub score
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: axel-op/dart-package-analyzer@v3
        id: workflow
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Check score
        env:
          TOTAL: ${{ steps.workflow.outputs.total }}
          TOTAL_MAX: ${{ steps.workflow.outputs.total_max }}
        run: |
          MISSING_POINTS=$(( $TOTAL_MAX - $TOTAL ))
          if (( MISSING_POINTS > 0 ))
          then
            echo Score can be improved!
            exit 1
          fi
